//! Policy → Seatbelt profile compiler (macos-enforcement §2.2). Pure.
//!
//! SBPL is last-match-wins, so explicit-deny-wins is realized by emitting
//! every allow first and every deny last. `(deny default)` is always the
//! baseline; category defaults of `allow` become explicit broad allows.

use super::baseline::{MACH_ALLOW, MACH_DENY, NEVER_ALLOW, RUNTIME_OPS};
use agentfence_policy::netpat::NetPattern;
use agentfence_policy::pathpat::{ancestors_inclusive, PatKind, PathPattern};
use agentfence_policy::set::{Matcher, PolicySet, Rule, Section};
use agentfence_policy::Effect;
use anyhow::{bail, Result};
use std::collections::BTreeSet;
use std::fmt::Write;

#[derive(Debug, Clone, Default)]
pub struct CompileInput<'a> {
    pub agent_id: &'a str,
    pub project: &'a str,
    pub proxy_port: u16,
    /// Provider-required Mach services (e.g. the keychain for Claude Code).
    pub mach_services: &'a [String],
    /// Canonical paths of executables denied by executable-only process rules.
    pub exec_deny_literals: &'a [String],
    /// Unix sockets that must never be connected to (ssh-agent, docker).
    pub socket_denies: &'a [String],
    /// Unix sockets the provider needs (e.g. keychain check).
    pub socket_allows: &'a [String],
    /// Extra read+write-denied literals (other names of hard-linked secrets).
    pub extra_denies: &'a [String],
    /// Session pty slave (ioctl allowed).
    pub pty_slave: Option<&'a str>,
    /// Session id stamped into every deny (`with message`) for attribution.
    pub session_tag: &'a str,
}

fn check(s: &str) -> Result<&str> {
    if s.chars().any(|c| c == '"' || c == '\\' || c.is_control()) {
        bail!("refusing to put {s:?} into a sandbox profile: it contains a quote, backslash or control character");
    }
    Ok(s)
}

fn lit(p: &str) -> Result<String> {
    Ok(format!("(literal \"{}\")", check(p)?))
}

fn path_filter(p: &PathPattern) -> Result<String> {
    Ok(match p.kind() {
        PatKind::Literal(l) => lit(l)?,
        PatKind::Subpath(s) => format!("(subpath \"{}\")", check(s)?),
        PatKind::Glob => {
            // regex literal: quotes are refused; backslashes are regex escapes we generated.
            check(p.source())?;
            format!("(regex #\"{}\")", p.sbpl_regex())
        }
    })
}

fn rule_filter(r: &Rule) -> Result<Option<String>> {
    let Matcher::Path(p) = &r.matcher else { return Ok(None) };
    let m = path_filter(p)?;
    if r.excepts.is_empty() {
        return Ok(Some(m));
    }
    let ex = r.excepts.iter().map(path_filter).collect::<Result<Vec<_>>>()?.join(" ");
    Ok(Some(format!("(require-all {m} (require-not (require-any {ex})))")))
}

fn fold(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '*' => "[^/]*".to_string(),
            '?' => "[^/]".to_string(),
            c if c.is_ascii_alphabetic() => format!("[{}{}]", c.to_ascii_lowercase(), c.to_ascii_uppercase()),
            c if "\\.+()[]{}^$|".contains(c) => format!("\\{c}"),
            c => c.to_string(),
        })
        .collect()
}

fn emit(out: &mut String, head: &str, filters: &[String]) {
    if filters.is_empty() {
        return;
    }
    let _ = writeln!(out, "({head}");
    for f in filters {
        let _ = writeln!(out, "  {f}");
    }
    out.push_str(")\n");
}

pub fn compile_profile(policy: &PolicySet, input: &CompileInput) -> Result<String> {
    let rules = policy.rules_for(input.agent_id, input.project);
    let defaults = policy.effective_defaults(input.agent_id, input.project);
    if defaults.process == Effect::Deny {
        bail!("`defaults.process: deny` is not supported by the seatbelt backend (it would need an exec allowlist); use process.deny rules instead");
    }
    let by = |section: Section, effects: &[Effect]| -> Vec<&Rule> {
        rules.iter().copied().filter(|r| r.section == section && effects.contains(&r.effect)).collect()
    };

    let mut out = String::new();
    out.push_str(";; Generated by AgentFence. Do not edit: regenerated for every session.\n(version 1)\n");
    if input.session_tag.is_empty() {
        out.push_str("(deny default)\n");
    } else {
        let _ = writeln!(out, "(deny default (with message \"af:{}|seatbelt-baseline|default\"))", check(input.session_tag)?);
    }
    out.push_str("\n;; ---- runtime baseline ----\n");
    for op in RUNTIME_OPS {
        out.push_str(op);
        out.push('\n');
    }
    out.push_str("(allow file-read-metadata (literal \"/var\") (literal \"/etc\") (literal \"/tmp\"))\n");
    let mut mach: BTreeSet<String> = MACH_ALLOW.iter().map(|s| s.to_string()).collect();
    for m in input.mach_services {
        if MACH_DENY.contains(&m.as_str()) {
            bail!("mach service {m} is on the deny list and cannot be allowed");
        }
        mach.insert(check(m)?.to_string());
    }
    let mach_f: Vec<String> = mach.iter().map(|m| format!("(global-name \"{m}\")")).collect();
    emit(&mut out, "allow mach-lookup", &mach_f);

    out.push_str("\n;; ---- category defaults ----\n");
    if defaults.filesystem == Effect::Allow {
        out.push_str("(allow file-read* file-write* file-map-executable)\n");
    }
    // `ask` for process defaults cannot be enforced by Seatbelt: it is
    // classified Observed and execs are allowed here.
    out.push_str("(allow process-exec*)\n");

    out.push_str("\n;; ---- allow rules ----\n");
    let reads = by(Section::FsRead, &[Effect::Allow]);
    let writes = by(Section::FsWrite, &[Effect::Allow]);
    let read_f = reads.iter().map(|r| rule_filter(r)).collect::<Result<Vec<_>>>()?.into_iter().flatten().collect::<Vec<_>>();
    let write_f = writes.iter().map(|r| rule_filter(r)).collect::<Result<Vec<_>>>()?.into_iter().flatten().collect::<Vec<_>>();
    emit(&mut out, "allow file-read* file-map-executable", &read_f);
    emit(&mut out, "allow file-read* file-write*", &write_f);
    // stat() of every ancestor of an allowed location (path resolution).
    let mut anc: BTreeSet<String> = BTreeSet::new();
    for r in reads.iter().chain(writes.iter()) {
        if let Matcher::Path(p) = &r.matcher {
            let top = match p.kind() {
                PatKind::Literal(l) => l.clone(),
                PatKind::Subpath(s) => s.clone(),
                PatKind::Glob => p.anchor().to_string(),
            };
            anc.extend(ancestors_inclusive(&top));
        }
    }
    let anc_f = anc.iter().map(|a| lit(a)).collect::<Result<Vec<_>>>()?;
    emit(&mut out, "allow file-read-metadata", &anc_f);
    let mut ioctl = vec![lit("/dev/tty")?, lit("/dev/dtracehelper")?];
    if let Some(p) = input.pty_slave {
        // The session's own terminal (never other /dev/ttys*: those are the human's).
        let _ = writeln!(out, "(allow file-read* file-write* {})", lit(p)?);
        ioctl.push(lit(p)?);
    }
    emit(&mut out, "allow file-ioctl", &ioctl);

    let _ = writeln!(out, "(allow network-outbound (remote ip \"localhost:{}\"))", input.proxy_port);
    for sock in input.socket_allows {
        let _ = writeln!(out, "(allow network-outbound (remote unix-socket (path-literal \"{}\")))", check(sock)?);
    }
    for r in by(Section::Listen, &[Effect::Allow]) {
        let Matcher::Net(n @ NetPattern::Addr { .. }) = &r.matcher else { continue };
        let Some(port) = n.port() else { bail!("network.listen entry {:?} needs an explicit port", r.written) };
        if !n.is_loopback_only() {
            bail!("network.listen entry {:?} is not loopback", r.written);
        }
        let _ = writeln!(out, "(allow network-bind network-inbound (local ip \"localhost:{port}\"))");
    }

    out.push_str("\n;; ---- deny rules (last: explicit deny wins) ----\n");
    // Each deny carries `(with message "af:<session>|<policy>|<rule>")`; the
    // kernel appends it to its violation report, which attributes the denial
    // to this session and rule exactly (no process tracking needed).
    let tag = |policy: &str, rule: &str| -> Result<String> {
        if input.session_tag.is_empty() {
            return Ok(String::new());
        }
        Ok(format!(" (with message \"af:{}|{}|{}\")", check(input.session_tag)?, check(policy)?, check(rule)?))
    };
    // Filesystem `ask` cannot prompt under Seatbelt: it fails closed (policy-model §6).
    let deny_read = by(Section::FsRead, &[Effect::Deny, Effect::Ask]);
    let deny_write = by(Section::FsWrite, &[Effect::Deny, Effect::Ask]);
    for (rules, ops) in [(&deny_read, "file-read* file-map-executable"), (&deny_write, "file-write*")] {
        for r in rules.iter() {
            if let Some(f) = rule_filter(r)? {
                let _ = writeln!(out, "(deny {ops}{} {f})", tag(&r.policy, &r.id)?);
            }
        }
    }
    // Location protection (policy-model §4): no unlink/rename/link of what a
    // deny protects, nor of any ancestor of it.
    for r in deny_read.iter().chain(deny_write.iter()) {
        let Matcher::Path(p) = &r.matcher else { continue };
        let mut filters = vec![rule_filter(r)?.unwrap_or_default()];
        for a in p.protected_ancestors() {
            filters.push(lit(&a)?);
        }
        emit(&mut out, &format!("deny file-write-unlink file-link{}", tag(&r.policy, &r.id)?), &filters);
    }
    let extra = input.extra_denies.iter().map(|p| lit(p)).collect::<Result<Vec<_>>>()?;
    emit(&mut out, &format!("deny file-read* file-write*{}", tag("builtin", "hardlink")?), &extra);

    for r in by(Section::Exec, &[Effect::Deny, Effect::Ask]) {
        let Matcher::Cmd(c) = &r.matcher else { continue };
        if !c.is_executable_only() {
            continue; // argument rules are observed, not compiled
        }
        let mut f = vec![];
        if let Some(name) = c.exe_basename_glob() {
            check(name)?;
            f.push(format!("(regex #\"/{}$\")", fold(name)));
            // PATH-resolved copies of this executable
            for l in input.exec_deny_literals.iter().filter(|l| l.rsplit('/').next().map(|b| c.matches(l, &[b.to_string()])).unwrap_or(false)) {
                f.push(lit(l)?);
            }
        }
        if let Some(abs) = c.exe_abs() {
            f.push(lit(abs)?);
        }
        emit(&mut out, &format!("deny process-exec*{}", tag(&r.policy, &r.id)?), &f);
    }

    let sock_f = input
        .socket_denies
        .iter()
        .map(|s| Ok(format!("(remote unix-socket (path-literal \"{}\"))", check(s)?)))
        .collect::<Result<Vec<_>>>()?;
    emit(&mut out, &format!("deny network-outbound{}", tag("builtin", "credential-socket")?), &sock_f);
    let mach_d: Vec<String> = MACH_DENY.iter().map(|m| format!("(global-name \"{m}\")")).collect();
    emit(&mut out, &format!("deny mach-lookup{}", tag("builtin", "mach-service")?), &mach_d);
    for op in NEVER_ALLOW {
        let _ = writeln!(out, "(deny {op}{})", tag("builtin", "never-allow")?);
    }
    Ok(out)
}
