#!/usr/bin/env bash
# Creates a disposable demo project with FAKE secrets and a demo policy.
# Safe to run repeatedly: it recreates $DEMO_DIR from scratch.
source "$(dirname "$0")/_lib.sh"

rm -rf "$DEMO_DIR"
# Created fresh and private; fails if someone recreated it in between.
mkdir -m 700 "$DEMO_DIR"
mkdir -p "$PROJECT" "$FAKE_HOME/.aws" "$FAKE_HOME/.ssh" "$AGENTACL_CONFIG_DIR" "$AGENTACL_HOME"
chmod 700 "$AGENTACL_CONFIG_DIR" "$AGENTACL_HOME"

# Fake values only: shaped like real ones so the demo reads naturally.
cat > "$PROJECT/.env" <<'F'
# FAKE demo secrets generated by AgentACL's setup-demo.sh
DATABASE_URL=postgres://demo:FAKE-db-password@localhost/app
STRIPE_SECRET_KEY=sk_test_FAKE0000000000000000000000
F
cat > "$FAKE_HOME/.aws/credentials" <<'F'
# FAKE demo credentials generated by AgentACL's setup-demo.sh
[default]
aws_access_key_id = AKIAFAKEFAKEFAKEFAKE
aws_secret_access_key = FAKE/secret/key/for/the/agentacl/demo00
F
printf 'FAKE demo SSH private key (not a real key)\n' > "$FAKE_HOME/.ssh/id_ed25519"
printf '# Demo app\nThis file is fine to read.\n' > "$PROJECT/README.md"
printf 'import sys\nprint(open(sys.argv[1]).read(), end="")\n' > "$PROJECT/read.py"
(cd "$PROJECT" && GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_NOSYSTEM=1 git init -q && git config user.email demo@example.com && git config user.name Demo)

# The demo policy: the built-in defaults (project open, everything else
# closed), plus rules that protect the fake home exactly like the built-ins
# protect the real one (the built-ins are rooted at your real home directory,
# which the demo never touches). `.env` is protected by the real built-in rule.
cat > "$AGENTACL_CONFIG_DIR/policy.yaml" <<F
version: v1
name: demo
defaults:
  filesystem: deny
  network: deny
  process: allow
filesystem:
  allow_read:  ["\${PROJECT}/**"]
  allow_write: ["\${PROJECT}/**"]
  deny_read:
    - { path: "$FAKE_HOME/.aws/**", reason: "Demo: stands in for ~/.aws (AWS credentials)" }
    - { path: "$FAKE_HOME/.ssh/**", reason: "Demo: stands in for ~/.ssh (SSH keys)" }
network:
  allow: ["example.com"]
F

bold "Demo ready in $DEMO_DIR"
dim  "  project:   $PROJECT   (.env, README.md, read.py)"
dim  "  fake home: $FAKE_HOME   (.aws/credentials, .ssh/id_ed25519)"
dim  "  every secret is FAKE; your real secrets are never read"
echo
echo "Next: scripts/demo/unprotected-secret-read.sh, then protected-secret-read.sh"
