//! A loaded, expanded, merged set of policy documents (policy-model §3).

use crate::error::PolicyError;
use crate::expand::{expand, Vars};
use crate::model::{Effect, Layer};
use crate::netpat::NetPattern;
use crate::pathpat::PathPattern;
use crate::procpat::CommandPattern;
use crate::raw::{parse_doc, RawDefaults, RawDoc, RawFs, RawNet, RawProc, RawRule};
use regex::Regex;
use serde::Serialize;
use sha2::{Digest, Sha256};

/// Built-in group names that `builtin.disable` may never name.
pub const UNDISABLEABLE: &[&str] = &["agentacl-self", "exec-persistence"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Section {
    FsRead,
    FsWrite,
    Exec,
    Net,
    Listen,
}

impl Section {
    pub fn as_str(self) -> &'static str {
        match self {
            Section::FsRead => "filesystem.read",
            Section::FsWrite => "filesystem.write",
            Section::Exec => "process.exec",
            Section::Net => "network.connect",
            Section::Listen => "network.listen",
        }
    }
}

#[derive(Debug, Clone)]
pub enum Matcher {
    Path(PathPattern),
    Cmd(CommandPattern),
    Net(NetPattern),
}

impl Matcher {
    pub fn source(&self) -> String {
        match self {
            Matcher::Path(p) => p.source().to_string(),
            Matcher::Cmd(c) => c.source().to_string(),
            Matcher::Net(n) => format!("{n:?}"),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Rule {
    pub id: String,
    pub policy: String,
    pub layer: Layer,
    pub section: Section,
    pub effect: Effect,
    pub matcher: Matcher,
    pub excepts: Vec<PathPattern>,
    pub reason: String,
    /// The pattern as written (before expansion), for display.
    pub written: String,
}

impl Rule {
    /// Path match honoring `except`.
    pub fn matches_path(&self, path: &str) -> bool {
        match &self.matcher {
            Matcher::Path(p) => p.matches(path) && !self.excepts.iter().any(|e| e.matches(path)),
            _ => false,
        }
    }
}

#[derive(Debug, Clone)]
pub struct Doc {
    pub name: String,
    pub layer: Layer,
    pub match_agents: Vec<Regex>,
    pub match_projects: Vec<PathPattern>,
    pub defaults: RawDefaults,
    pub rules: Vec<Rule>,
    pub disable_builtin: Vec<String>,
}

impl Doc {
    pub fn applies_to(&self, agent_id: &str, project: &str) -> bool {
        (self.match_agents.is_empty() || self.match_agents.iter().any(|r| r.is_match(agent_id))) && (self.match_projects.is_empty() || self.match_projects.iter().any(|p| p.matches(project)))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PolicySource {
    pub layer: Layer,
    pub name: String,
    pub yaml: String,
}

/// A document generated by AgentACL itself (provider runtime requirements,
/// per-session grants). Loaded at the Builtin layer and shown by `policy check`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct GeneratedDoc {
    pub name: String,
    pub allow_read: Vec<String>,
    pub allow_write: Vec<String>,
    pub deny_write: Vec<String>,
    pub net_allow: Vec<String>,
    pub reason: String,
}

#[derive(Debug, Clone, Default)]
pub struct LoadOptions {
    /// sha256 (hex) of raw project-policy file bytes the user has trusted.
    pub trusted_project_sha256: Vec<String>,
    pub generated: Vec<GeneratedDoc>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct Defaults {
    pub filesystem: Effect,
    pub network: Effect,
    pub process: Effect,
}

/// Used when no applicable document sets a category default (policy-model §4).
pub const FALLBACK_DEFAULTS: Defaults = Defaults { filesystem: Effect::Deny, network: Effect::Deny, process: Effect::Allow };

#[derive(Debug, Clone)]
pub struct PolicySet {
    pub docs: Vec<Doc>,
    pub sha256: String,
}

const BUILTINS: &[(&str, &str)] = &[
    ("protect-secrets", include_str!("../builtin/protect-secrets.yaml")),
    ("exec-persistence", include_str!("../builtin/exec-persistence.yaml")),
    ("agentacl-self", include_str!("../builtin/agentacl-self.yaml")),
    ("runtime", include_str!("../builtin/runtime.yaml")),
];
const DEFAULT_POLICY: &str = include_str!("../builtin/default.yaml");

pub fn builtin_sources(include_default: bool) -> Vec<PolicySource> {
    let mut v: Vec<PolicySource> = BUILTINS.iter().map(|(n, y)| PolicySource { layer: Layer::Builtin, name: (*n).into(), yaml: (*y).into() }).collect();
    if include_default {
        v.push(PolicySource { layer: Layer::Builtin, name: "default".into(), yaml: DEFAULT_POLICY.into() });
    }
    v
}

/// Names of the groups defined by the built-in protect-secrets policy.
pub fn protect_secrets_groups() -> Vec<String> {
    let raw = parse_doc(BUILTINS[0].1, Layer::Builtin, "protect-secrets").expect("builtin parses");
    let mut groups: Vec<String> = raw.filesystem.deny_read.iter().filter_map(|r| r.id.clone()).collect();
    groups.dedup();
    groups
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

fn glob_regex(g: &str) -> Regex {
    let body: String = g
        .chars()
        .map(|c| match c {
            '*' => ".*".to_string(),
            '?' => ".".to_string(),
            c => regex::escape(&c.to_string()),
        })
        .collect();
    Regex::new(&format!("^{body}$")).expect("escaped glob is a valid regex")
}

struct Compiler<'a> {
    vars: &'a Vars,
    doc: String,
    layer: Layer,
}

impl Compiler<'_> {
    fn bad(&self, pattern: &str, msg: String) -> PolicyError {
        PolicyError::BadPattern { doc: self.doc.clone(), pattern: pattern.into(), msg }
    }

    fn path(&self, s: &str) -> Result<PathPattern, PolicyError> {
        let e = expand(s, self.vars, &self.doc)?;
        PathPattern::parse(&e).map_err(|m| self.bad(s, m))
    }

    fn rules(&self, out: &mut Vec<Rule>, section: Section, effect: Effect, key: &str, raws: &[RawRule]) -> Result<(), PolicyError> {
        for (i, r) in raws.iter().enumerate() {
            let matcher = match section {
                Section::FsRead | Section::FsWrite => Matcher::Path(self.path(&r.pattern)?),
                Section::Exec => {
                    let e = expand(&r.pattern, self.vars, &self.doc)?;
                    Matcher::Cmd(CommandPattern::parse(&e.text).map_err(|m| self.bad(&r.pattern, m))?)
                }
                Section::Net | Section::Listen => {
                    let n = NetPattern::parse(&r.pattern).map_err(|m| self.bad(&r.pattern, m))?;
                    if section == Section::Listen && !n.is_loopback_only() {
                        return Err(self.bad(&r.pattern, "network.listen only accepts loopback addresses".into()));
                    }
                    Matcher::Net(n)
                }
            };
            let excepts = match &matcher {
                Matcher::Path(p) => r
                    .except
                    .iter()
                    .map(|x| {
                        if x.starts_with("**/") {
                            PathPattern::parse_except(x, p.anchor()).map_err(|m| self.bad(x, m))
                        } else if x.starts_with('/') || x.starts_with("${") {
                            self.path(x)
                        } else {
                            Err(self.bad(x, "except entries must be absolute or start with `**/`".into()))
                        }
                    })
                    .collect::<Result<Vec<_>, _>>()?,
                _ => vec![],
            };
            out.push(Rule {
                id: r.id.clone().unwrap_or_else(|| format!("{}/{key}/{i}", self.doc)),
                policy: self.doc.clone(),
                layer: self.layer,
                section,
                effect,
                matcher,
                excepts,
                reason: r.reason.clone().unwrap_or_else(|| format!("{} rule in policy {}", effect.as_str(), self.doc)),
                written: r.pattern.clone(),
            });
        }
        Ok(())
    }
}

fn compile_doc(raw: &RawDoc, vars: &Vars) -> Result<Doc, PolicyError> {
    let c = Compiler { vars, doc: raw.name.clone(), layer: raw.layer };
    let mut rules = Vec::new();
    let RawFs { allow_read, allow_write, deny_read, deny_write } = &raw.filesystem;
    let RawProc { allow, deny, require_approval } = &raw.process;
    let RawNet { allow: nallow, deny: ndeny, listen } = &raw.network;
    c.rules(&mut rules, Section::FsRead, Effect::Deny, "filesystem.deny_read", deny_read)?;
    c.rules(&mut rules, Section::FsWrite, Effect::Deny, "filesystem.deny_write", deny_write)?;
    c.rules(&mut rules, Section::FsRead, Effect::Allow, "filesystem.allow_read", allow_read)?;
    c.rules(&mut rules, Section::FsWrite, Effect::Allow, "filesystem.allow_write", allow_write)?;
    c.rules(&mut rules, Section::Exec, Effect::Deny, "process.deny", deny)?;
    c.rules(&mut rules, Section::Exec, Effect::Ask, "process.require_approval", require_approval)?;
    c.rules(&mut rules, Section::Exec, Effect::Allow, "process.allow", allow)?;
    c.rules(&mut rules, Section::Net, Effect::Deny, "network.deny", ndeny)?;
    c.rules(&mut rules, Section::Net, Effect::Allow, "network.allow", nallow)?;
    c.rules(&mut rules, Section::Listen, Effect::Allow, "network.listen", listen)?;

    let (match_agents, match_projects) = match &raw.match_ {
        Some(m) => (m.agents.iter().map(|a| glob_regex(a)).collect(), m.projects.iter().map(|p| c.path(p)).collect::<Result<Vec<_>, _>>()?),
        None => (vec![], vec![]),
    };
    let disable_builtin = raw.builtin.as_ref().map(|b| b.disable.clone()).unwrap_or_default();
    Ok(Doc { name: raw.name.clone(), layer: raw.layer, match_agents, match_projects, defaults: raw.defaults, rules, disable_builtin })
}

fn generated_raw(g: &GeneratedDoc) -> RawDoc {
    let rule = |p: &String| RawRule { kind: crate::raw::RuleKind::Path, pattern: p.clone(), except: vec![], id: Some("runtime-requirement".into()), reason: Some(g.reason.clone()) };
    let protect = |p: &String| RawRule { id: Some("protected-config".into()), reason: Some("Agent configuration that runs code later is protected".into()), ..rule(p) };
    let host = |p: &String| RawRule { kind: crate::raw::RuleKind::Host, ..rule(p) };
    let mut read = g.allow_read.clone();
    read.extend(g.allow_write.iter().cloned());
    RawDoc {
        name: g.name.clone(),
        layer: Layer::Builtin,
        match_: None,
        defaults: RawDefaults::default(),
        filesystem: RawFs {
            allow_read: read.iter().map(rule).collect(),
            allow_write: g.allow_write.iter().map(rule).collect(),
            deny_read: vec![],
            deny_write: g.deny_write.iter().map(protect).collect(),
        },
        process: RawProc::default(),
        network: RawNet { allow: g.net_allow.iter().map(host).collect(), deny: vec![], listen: vec![] },
        builtin: None,
    }
}

fn merge_defaults(docs: &[&Doc]) -> Defaults {
    let pick = |f: fn(&RawDefaults) -> Option<Effect>, fallback: Effect| docs.iter().filter_map(|d| f(&d.defaults)).max_by_key(|e| e.restrictiveness()).unwrap_or(fallback);
    Defaults { filesystem: pick(|d| d.filesystem, FALLBACK_DEFAULTS.filesystem), network: pick(|d| d.network, FALLBACK_DEFAULTS.network), process: pick(|d| d.process, FALLBACK_DEFAULTS.process) }
}

#[derive(Serialize)]
struct CanonRule<'a> {
    id: &'a str,
    section: Section,
    effect: Effect,
    pattern: String,
    excepts: Vec<&'a str>,
}
#[derive(Serialize)]
struct CanonDoc<'a> {
    name: &'a str,
    layer: Layer,
    agents: Vec<&'a str>,
    projects: Vec<&'a str>,
    defaults: [Option<Effect>; 3],
    disable: &'a [String],
    rules: Vec<CanonRule<'a>>,
}

impl PolicySet {
    pub fn load(sources: Vec<PolicySource>, vars: &Vars, opts: &LoadOptions) -> Result<PolicySet, PolicyError> {
        let mut raws: Vec<RawDoc> = Vec::new();
        let mut project_raws: Vec<RawDoc> = Vec::new();
        for src in &sources {
            match src.layer {
                Layer::Project => {
                    let trusted = opts.trusted_project_sha256.iter().any(|h| h.eq_ignore_ascii_case(&sha256_hex(src.yaml.as_bytes())));
                    if trusted {
                        raws.push(parse_doc(&src.yaml, Layer::User, &src.name)?);
                    } else {
                        project_raws.push(parse_doc(&src.yaml, Layer::Project, &src.name)?);
                    }
                }
                layer => raws.push(parse_doc(&src.yaml, layer, &src.name)?),
            }
        }
        for g in &opts.generated {
            raws.push(generated_raw(g));
        }

        let mut docs = raws.iter().map(|r| compile_doc(r, vars)).collect::<Result<Vec<_>, _>>()?;

        // Validate builtin.disable.
        let groups = protect_secrets_groups();
        for d in &docs {
            for g in &d.disable_builtin {
                if UNDISABLEABLE.contains(&g.as_str()) {
                    return Err(PolicyError::Invalid { doc: d.name.clone(), msg: format!("built-in group `{g}` cannot be disabled") });
                }
                if !groups.contains(g) {
                    return Err(PolicyError::Invalid { doc: d.name.clone(), msg: format!("unknown built-in group `{g}`") });
                }
            }
        }

        // Project defaults may only tighten the merged built-in + user value.
        let base = merge_defaults(&docs.iter().collect::<Vec<_>>());
        for raw in &project_raws {
            for (cat, val, cur) in [("filesystem", raw.defaults.filesystem, base.filesystem), ("network", raw.defaults.network, base.network), ("process", raw.defaults.process, base.process)] {
                if let Some(v) = val {
                    if v.restrictiveness() < cur.restrictiveness() {
                        return Err(PolicyError::ProjectForbidden { doc: raw.name.clone(), key: format!("defaults.{cat}") });
                    }
                }
            }
            docs.push(compile_doc(raw, vars)?);
        }
        // Load order: Builtin, User, Project (stable within a layer).
        docs.sort_by_key(|d| d.layer);

        let canon: Vec<CanonDoc> = docs
            .iter()
            .map(|d| CanonDoc {
                name: &d.name,
                layer: d.layer,
                agents: d.match_agents.iter().map(|r| r.as_str()).collect(),
                projects: d.match_projects.iter().map(|p| p.source()).collect(),
                defaults: [d.defaults.filesystem, d.defaults.network, d.defaults.process],
                disable: &d.disable_builtin,
                rules: d
                    .rules
                    .iter()
                    .map(|r| CanonRule { id: &r.id, section: r.section, effect: r.effect, pattern: r.matcher.source(), excepts: r.excepts.iter().map(|e| e.source()).collect() })
                    .collect(),
            })
            .collect();
        let sha256 = sha256_hex(&serde_json::to_vec(&canon).expect("serializable"));
        Ok(PolicySet { docs, sha256 })
    }

    pub fn applicable<'a>(&'a self, agent_id: &str, project: &str) -> Vec<&'a Doc> {
        self.docs.iter().filter(|d| d.layer == Layer::Builtin || d.applies_to(agent_id, project)).collect()
    }

    pub fn effective_defaults(&self, agent_id: &str, project: &str) -> Defaults {
        merge_defaults(&self.applicable(agent_id, project))
    }

    /// Effective rules in load order, with disabled protect-secrets groups removed.
    pub fn rules_for<'a>(&'a self, agent_id: &str, project: &str) -> Vec<&'a Rule> {
        let docs = self.applicable(agent_id, project);
        let disabled: Vec<&String> = docs.iter().flat_map(|d| d.disable_builtin.iter()).collect();
        docs.iter().flat_map(|d| d.rules.iter()).filter(|r| !(r.policy == "protect-secrets" && disabled.contains(&&r.id))).collect()
    }

    pub fn disabled_groups(&self, agent_id: &str, project: &str) -> Vec<String> {
        self.applicable(agent_id, project).iter().flat_map(|d| d.disable_builtin.iter().cloned()).collect()
    }
}
